// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5rjAxuYvgZBXsWtgDiRChCq8mqtKckzA',
    appId: '1:919292181373:android:c4e1f77120a3c34061ea14',
    messagingSenderId: '919292181373',
    projectId: 'ehh-sleepers-shn',
    storageBucket: 'ehh-sleepers-shn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0TUuSHEKy7R4Yss-9T3PWac21LngeqRo',
    appId: '1:919292181373:ios:2d4a1ce5737d7a4361ea14',
    messagingSenderId: '919292181373',
    projectId: 'ehh-sleepers-shn',
    storageBucket: 'ehh-sleepers-shn.appspot.com',
    androidClientId: '919292181373-1h164iqt2ntj7bsq9ol1or74rvnvpoj6.apps.googleusercontent.com',
    iosClientId: '919292181373-7s262psceefa1okrktpvm7ckn0rnai3b.apps.googleusercontent.com',
    iosBundleId: 'com.example.ehh',
  );
}
